- name: database execution query
  hosts: mysql
  become: yes
  tasks: 
  - name: install MYSQL libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.12
    loop:
    - cryptography
    - PyMySQL

  - name: Insert Record in database
    community.mysql.mysql_query:
      login_host: mysql.learndevopsacademy.online
      login_user: root
      query: CREATE USER 'root'@'%' IDENTIFIED BY 'Harini@2024'