- name: database execution query
  hosts: mysql
  become: yes
  tasks: 
  - name: Install Python 3.9 and pip
    ansible.builtin.package:
      name: "{{ item }}"
    loop:
      - python3.9
      - python3.9-distutils
      - python3.9-venv

  - name: Install pip3.9
    ansible.builtin.command: curl -sS https://bootstrap.pypa.io/get-pip.py | python3.9

  - name: install MYSQL libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL
  - name: Insert Record in database
    community.mysql.mysql_query:
      login_host: mysql.learndevopsacademy.online
      login_user: root
      query: CREATE USER 'root'@'%' IDENTIFIED BY 'Harini@2024'