- name: Install Python 3.9 and dependencies
  hosts: mysql
  become: yes
  tasks:
- name: Create a virtual environment
  command:
    cmd: python3 -m venv /path/to/your/venv
    creates: /path/to/your/venv/bin/activate
    
- name: Activate virtual environment and install dependencies
  shell: |
    source /path/to/your/venv/bin/activate
    pip install cryptography PyMySQL


