- name: configure mysql server configuration
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
  - name: Install MySQL libraries with pip and override restrictions
    ansible.builtin.command:
      cmd: /usr/bin/pip3 install cryptography PyMySQL --break-system-packages
    
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes
  
  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_host: mysql.learndevopsacademy.online
      login_password: "{{ mysql_root_password }}"
    register: mysql_info
    ignore_errors: true

  - name: print the output details
    ansible.builtin.debug:
      msg: "MYSQL info: {{ mysql_info }}"

