- name: configure Mysql
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
  - name: install python package manager
    ansible.builtin.package:
      name: python3-pip
      state: installed

  - name: install MYSQL libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL
       
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: mysql.learndevopsacademy.online
    register: mysql_info
    ignore_errors: true

  - name: print the output details
    ansible.builtin.debug:
      msg: "MYSQL info: {{ mysql_info }}"
    
  - name: create database user and password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true

