- name: update MySQL configiration
  hosts: mysql
  become: yes
  tasks:
  - name: update bind-address in mysql configuration
    ansible.builtin.replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address\s*=\s*.*'
      replace: 'bind-address              =0.0.0.0'
  
  -name: update mysqlx-bind-address in mysql configuration
    ansible.builtin.replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^mysqlx-bind-address\s*=\s*.*'
      replace: 'mysqlx-bind-address       =0.0.0.0'

  - name: restart mysql service
    ansible.builtin.service:
      name: mysql
      state: restarted


      