#This YAML file should run only if the servers are UBUNTU. We have to replace the mysqlx-bind-address and bind-address in MYSQL
#configuration from 127.0.0.1 to 0.0.0.0 so that any one from outside also can able to connect to this database. if we not changed this
#file it will not work(but in LIVE PRODUCTION this is not recommendable). make sure to run this YAML file only after 
#"mysql-ubuntu.yaml" file.


- name: update MySQL configiration
  hosts: mysql
  become: yes
  tasks:
  - name: update bind-address in mysql configuration
    ansible.builtin.replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address\s*=\s*.*'
      replace: 'bind-address              =0.0.0.0'
  
  - name: update mysqlx-bind-address in mysql configuration
    ansible.builtin.replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^mysqlx-bind-address\s*=\s*.*'
      replace: 'mysqlx-bind-address       =0.0.0.0'

  - name: restart mysql service
    ansible.builtin.service:
      name: mysql
      state: restarted


      